[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.33"
optimizer = true
optimizer_runs = 9999999
via_ir = true
evm_version = "osaka"
verbosity = 2
fs_permissions = [{ access = "read", path = "./" }]
